import Head from 'next/head';
import Link from 'next/link';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillInstagram } from 'react-icons/ai'
import Image from "next/image";
import Shop1 from "../public/Shop1.jpg";
import Mix1 from "../public/Mix1.jpg";
import Swag1 from "../public/Swag1.jpg";
import Lounge1 from "../public/Lounge1.jpg";
import Rndcard from "../public/Rndcard.jpg";
import { useState } from "react";
import Bombay from "../public/flowerpictures/Bombay.jpg"

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={ darkMode ? "dark" : "" }>
      <Head>
        <title>Reggie and Dro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-slate-300 px-10 md:px-10 lg:px-40 dark:bg-gray-900">
        <section className=' min-h-screen'>
        <nav className='lg:text-4xl md:text-2xl sm:text-lg sm:text-center sm:tracking-wider  flex justify-evenly md:mx-auto bg-gradient-to-r from-green-500 to-purple-900 rounded-lg'>
            {/* <h1 className='text-2xl bg-gradient-to-r from-green-500 to-green-900 rounded-md text-purple-600'>Reggie and Dro</h1> */}
            <ul className='flex items-center'>
              <li className=' text-purple-700 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold'><a href="/">Reggie and Dro</a></li>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li><a className='text-purple-600 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold' href="#">Gear</a></li>
              <li><a className='text-green-600 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold' href='/smoke'>Smoke</a></li>
              <li><a className='text-green-700 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold' href='/about'>How it is legal?</a></li>
            </ul>
          </nav>
          <div className='flex justify-center py-2'>
          <Image className=''src={Rndcard} width={500} height={500} />
          </div>
          <div className="text-center p-10">
            <h2 className='text-4xl br-10 py-2 dark:text-amber-700'>San Antonio Smokers Social!</h2>
            <p className="py-5 leading-8 md:text-xl max-w-xl mx-auto dark:text-amber-700">Welcome to the first Cannabis Store and Social club in San Antonio, Texas. Come for the flower and stay for the good vibes. With over <strong>100 Flavors of flower in house</strong>.</p>
          </div>
          <div className="text-5xl flex justify-center gap-8 py-3 text-indigo-900 dark:text-fuchsia-600 ">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
            <AiFillInstagram />
          </div>
          <div className='relative mx-auto bg-graident-to-b from-slate-400 rounded-full w-100 h-100 mt-10'>
            <Image src={Shop1}/>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-2xl py-5 leading-10 flex justify-center dark:text-indigo-400">See the best views of the shop</h3>
          </div>
          <div className="lg:flex gap-10">
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <a href="/about">
              <Image className="" src={Bombay} width={250} height={250}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-indigo-400'>Enjoy how you like with</h3>
              <p className='py-1 dark:text-indigo-400'>Edibles</p>
              <p className='py-1 dark:text-indigo-400'>Vapes</p>
              <p className='py-1 dark:text-indigo-400'>Hemp Smokes</p>
              <p className='py-1 dark:text-indigo-400'>Pre rolled</p>
              </a>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className="" src={Swag1} width={250} height={250}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-indigo-400'>With Subliminated Gears such as</h3>
              <p className='py-1 dark:text-indigo-400'>T-shirts</p>
              <p className='py-1 dark:text-indigo-400'>Caps</p>
              <p className='py-1 dark:text-indigo-400'>Beanies</p>
              <p className='py-1 dark:text-indigo-400'>Sweaters</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className="" src={Lounge1} width={250} height={250}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-indigo-400'>With good spots to relax</h3>
              <p className='py-1 dark:text-indigo-400'>Classic 8track</p>
              <p className='py-1 dark:text-indigo-400'>Mounted Tvs</p>
              <p className='py-1 dark:text-indigo-400'>Bongs on Deck</p>
              <p className='py-1 dark:text-indigo-400'>Jars of the best</p>
            </div>
          </div>
          <footer>
          {/* <iframe width="440" height="440" src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=en&amp;q=%2019141%20Stone%20Oak%20Pkwy%20%23403%20San%20Antonio%2C%20TX%2078258+(Reggie%20and%20Dro)&amp;ie=UTF8&amp;t=&amp;z=13&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe> */}
          </footer>
        </section>
      </main>
    </div>
  );
}
