import Head from 'next/head';
import Link from 'next/link';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Image from "next/image";
import { useState } from "react";
import Hempress3 from "../public/flowerpictures/Hempress3Indoor.jpg"

//First set
import Bombay from "../public/flowerpictures/Bombay.jpg"
import Bubba77 from "../public/flowerpictures/Bubba77.jpg"
import Blueberry1 from "../public/flowerpictures/BlueberryKushMints.jpg"

//Second Set
import Bombpop1 from "../public/flowerpictures/BombPop.jpg"
import BubbaS from "../public/flowerpictures/BubbaSuver.jpg"
import Bubski from "../public/flowerpictures/BubskiSmalls.jpg"

//Third Set
import ChicaPs from "../public/flowerpictures/ChicaPiss.jpg"
import ChicaPo from "../public/flowerpictures/ChicaPoo.jpg"
import Chiesel from "../public/flowerpictures/Chiesel.jpg"

export default function smoke() {

  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={ darkMode ? "dark" : "" }>
      <Head>
        <title>Reggie and Dro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-slate-300 px-10 md:px-10 lg:px-40 dark:bg-gray-900">
        <section className=' min-h-screen'>
        <nav className='lg:text-4xl md:text-2xl sm:text-lg sm:text-center sm:tracking-wider  flex justify-evenly md:mx-auto bg-gradient-to-r from-green-500 to-purple-900 rounded-lg'>
            {/* <h1 className='text-2xl bg-gradient-to-r from-green-500 to-green-900 rounded-md text-purple-600'>Reggie and Dro</h1> */}
            <ul className='flex items-center'>
              <li className=' text-purple-700 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold'><a href="/">Reggie and Dro</a></li>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li><a className='text-purple-600 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold' href="#">Gear</a></li>
              <li><a className='text-green-600 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold' href='/smoke'>Smoke</a></li>
              <li><a className='text-green-700 px-4 py-2 hover:animate-pulse hover:brightness-200 font-extrabold' href='/about'>How it is legal?</a></li>
            </ul>
          </nav>
          <h3 className='text-4xl text-center font-extrabold py-2 tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-green-700 to-purple-700'>Hempress 3</h3>
          <div className='flex justify-center py-2'>
          <Image className=''src={Hempress3} width={500} height={500} />
          </div>

          <h2 className='text-4xl text-center font-extrabold py-2 tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-green-700 to-purple-700'>The best from every shelf</h2>

          
          <div className='bg-slate-400 dark:bg-gradient-to-br from-amber-400 to-amber-500 w-full h-auto flex flex-row justify-evenly p-2'>
            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={Bubba77} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Bubba77</h2>
                    <p>Product Details</p>
                </div>
            </div>

            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={Blueberry1} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>BlueberryKushMints</h2>
                    <p>Product Details</p>
                </div>
            </div>

            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={Bombay} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Bombay</h2>
                    <p>Product Details</p>
                </div>
            </div>

          </div>

          {/* Second Set */}
          <div className='bg-slate-400 dark:bg-gradient-to-br from-amber-500 to-amber-600 w-full h-auto flex flex-row justify-evenly p-2'>
            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={BubbaS} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Bubba Suver</h2>
                    <p>Product Details</p>
                </div>
            </div>

            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={Bubski} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Bubski Smalls</h2>
                    <p>Product Details</p>
                </div>
            </div>

            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={Bombpop1} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>BombPop</h2>
                    <p>Product Details</p>
                </div>
            </div>
        </div>

        {/* Third Set */}
        <div className='bg-slate-400 dark:bg-gradient-to-br from-amber-600 to-amber-700 w-full h-auto flex flex-row justify-evenly p-2'>
            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={ChicaPs} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Chica Piss</h2>
                    <p>Product Details</p>
                </div>
            </div>

            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={ChicaPo} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Chica Poo</h2>
                    <p>Product Details</p>
                </div>
            </div>

            <div className='w-60 p-2 bg-white rounded-xl transform transition-all hover:translate-y-2 duration-500 shadow-xl hover:shadow-2xl'>
                <Image src={Chiesel} />
                <div className='p-2'>
                    <h2 className='font-bold text-lg'>Chiesel</h2>
                    <p>Product Details</p>
                </div>
            </div>
        </div>
        

        
        </section>
      </main>
    </div>
  );
}